
async function ensureFreshBuild(){
  const BUILD='8';
  if(!sessionStorage.getItem('academyHardRefreshV9')){
    sessionStorage.setItem('academyHardRefreshV9','1');
    try{
      if('serviceWorker' in navigator){
        const regs=await navigator.serviceWorker.getRegistrations();
        await Promise.all(regs.map(r=>r.unregister()));
      }
      if(window.caches){
        const keys=await caches.keys();
        await Promise.all(keys.map(k=>caches.delete(k)));
      }
    }catch(e){}
    location.reload();
    return false;
  }
  return true;
}


const S={data:null,tab:'today',selectedDay:null,timer:null,timerLeft:0,timerRunning:false};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const store={get:(k,d=null)=>{try{let v=localStorage.getItem(k);return v===null?d:JSON.parse(v)}catch{return d}},set:(k,v)=>localStorage.setItem(k,JSON.stringify(v))};
function toast(t='Сохранено'){let e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1200)}
function esc(s=''){return s.replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function startDate(){return store.get('startDate',null)}
function currentDay(){let sd=startDate(); if(!sd)return 1; let a=new Date(sd+'T00:00:00'), b=new Date(); b.setHours(0,0,0,0); return Math.max(1,Math.min(365,Math.floor((b-a)/86400000)+1))}
function dayDone(day){let d=S.data.days[day-1], p=store.get('checks',{}), total=0,done=0;d.sections.forEach((s,si)=>s.items.forEach((it,ii)=>{total++; if(p[`${day}-${si}-${ii}`])done++}));return total>0&&done===total}
function dayPct(day){let d=S.data.days[day-1], p=store.get('checks',{}), total=0,done=0;d.sections.forEach((s,si)=>s.items.forEach((it,ii)=>{total++; if(p[`${day}-${si}-${ii}`])done++}));return total?Math.round(done/total*100):0}
function totalPct(){let done=S.data.days.filter(d=>dayDone(d.day)).length;return Math.round(done/365*100)}
function render(){ $$('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===S.tab)); if(S.tab==='today')renderToday(); else if(S.tab==='course')renderCourse(); else if(S.tab==='journal')renderJournal(); else if(S.tab==='progress')renderProgress(); else renderMore(); }
function renderToday(){let d=S.data.days[currentDay()-1], sd=startDate(); let h=`<section class="hero"><div class="row between"><span class="eyebrow">${esc(d.phase||'ACADEMY')}</span>${d.is_exam?'<span class="exam-badge">ЭКЗАМЕН</span>':d.is_mission?'<span class="mission-badge">МИССИЯ</span>':''}</div><h1>День ${d.day}</h1><div class="muted">Неделя ${d.week} · ${esc(d.weekday)}${d.meta?' · '+esc(d.meta.replace(/^Фаза:[^.]+\.?\s*/,'').slice(0,90)):''}</div><div style="height:14px"></div><div class="row between"><span class="small">Выполнено сегодня</span><b>${dayPct(d.day)}%</b></div><div class="progress" style="margin-top:8px"><span style="width:${dayPct(d.day)}%"></span></div>${!sd?`<button class="btn install" onclick="beginCourse()">Начать курс сегодня</button><div class="notice">Дата старта пока не установлена. Можно посмотреть День 1, а после нажатия приложение будет автоматически открывать текущий день.</div>`:''}</section>`;
 h+=renderDay(d,true); h+=`<div class="card" style="margin-top:12px"><h3>Таймер занятия</h3><div class="timer" id="timerText">${fmtTimer(S.timerLeft)}</div><div class="timer-controls"><button class="btn secondary" onclick="setTimer(10)">10 мин</button><button class="btn secondary" onclick="setTimer(25)">25 мин</button><button class="btn secondary" onclick="setTimer(45)">45 мин</button></div><div class="timer-controls" style="margin-top:8px"><button class="btn" onclick="toggleTimer()">${S.timerRunning?'Пауза':'Старт'}</button><button class="btn ghost" onclick="resetTimer()">Сброс</button></div></div>`;
 $('#screen').innerHTML=h; $('#topSub').textContent=`День ${d.day} из 365 · ${totalPct()}% курса`;}
function linkify(t){let x=esc(t);return x.replace(/(https?:\/\/[^\s<]+)/g,'<a class="source" target="_blank" rel="noopener" href="$1">$1</a>')} function renderDay(d,checkable=false){let checks=store.get('checks',{});let h='';d.sections.forEach((s,si)=>{h+=`<section class="section-card"><div class="section-head">${esc(s.title)}</div>`; if(!s.items.length)h+='<div class="task"><span>Раздел дня</span></div>'; s.items.forEach((it,ii)=>{let key=`${d.day}-${si}-${ii}`, done=!!checks[key];h+=`<label class="task ${done?'done':''}">${checkable?`<input type="checkbox" ${done?'checked':''} onchange="toggleTask('${key}',this)">`:''}<span>${linkify(it)}</span></label>`});h+='</section>'});return h}
function toggleTask(k,el){let c=store.get('checks',{});c[k]=el.checked;store.set('checks',c);el.closest('.task').classList.toggle('done',el.checked);let d=currentDay(); let bar=$('.hero .progress span');if(bar){let p=dayPct(d);bar.style.width=p+'%';let b=$('.hero .row.between b'); if(b)b.textContent=p+'%'}toast(el.checked?'Отмечено':'Снято')}
function beginCourse(){let dt=new Date(), y=dt.getFullYear(),m=String(dt.getMonth()+1).padStart(2,'0'),d=String(dt.getDate()).padStart(2,'0');store.set('startDate',`${y}-${m}-${d}`);toast('Курс начат');render()}
function renderCourse(){let cur=currentDay(), phase='ALL';let phases=[...new Set(S.data.days.map(d=>d.phase).filter(Boolean))];let h=`<section class="hero"><div class="eyebrow">CURRICULUM</div><h1>365 дней</h1><div class="muted">Открой любой день. Текущий день отмечен рамкой.</div><div class="calendar-controls"><select id="phaseFilter"><option value="ALL">Все фазы</option>${phases.map(p=>`<option>${esc(p)}</option>`).join('')}</select><input id="daySearch" inputmode="numeric" placeholder="День №"></div></section><div id="courseList"></div>`;$('#screen').innerHTML=h;$('#topSub').textContent='Полный учебный план';$('#phaseFilter').onchange=drawCourse;$('#daySearch').oninput=drawCourse;drawCourse();}
function drawCourse(){let phase=$('#phaseFilter')?.value||'ALL',q=parseInt($('#daySearch')?.value||'0'),cur=currentDay();let list=S.data.days.filter(d=>(phase==='ALL'||d.phase===phase)&&(!q||d.day===q));let groups={};list.forEach(d=>(groups[d.week]??=[]).push(d));let h='';Object.entries(groups).forEach(([w,ds])=>{h+=`<div class="card" style="margin-top:12px"><div class="row between"><h3>Неделя ${w}</h3><span class="muted small">${esc(ds[0].phase||'')}</span></div><div class="day-list">${ds.map(d=>`<button class="day-chip ${dayDone(d.day)?'done':''} ${d.day===cur?'current':''} ${d.is_exam?'exam':''}" onclick="openDay(${d.day})">${d.day}</button>`).join('')}</div></div>`});$('#courseList').innerHTML=h||'<div class="empty">Ничего не найдено</div>'}
function openDay(n){let d=S.data.days[n-1];$('#modalBox').innerHTML=`<div class="row between"><div><div class="eyebrow">${esc(d.phase||'')}</div><h2>День ${d.day} · ${esc(d.weekday)}</h2></div><button class="btn ghost" onclick="closeModal()">Закрыть</button></div>${renderDay(d,false)}`;$('#modal').classList.remove('hidden')}
function closeModal(){$('#modal').classList.add('hidden')}
function renderJournal(){let d=currentDay(), all=store.get('journal',{}),j=all[d]||{};$('#topSub').textContent=`Agent Log · День ${d}`;$('#screen').innerHTML=`<section class="hero"><div class="eyebrow">AGENT LOG</div><h1>День ${d}</h1><div class="muted">Короткий служебный разбор дня. Записи остаются только на этом устройстве.</div></section><div class="card" style="margin-top:12px"><div class="label">COMPLETED — что выполнено?</div><textarea id="jCompleted">${esc(j.completed||'')}</textarea><div class="label">LEARNED — что нового?</div><textarea id="jLearned">${esc(j.learned||'')}</textarea><div class="label">ERROR — главная ошибка</div><textarea id="jError">${esc(j.error||'')}</textarea><div class="label">ADJUSTMENT — что изменить завтра?</div><textarea id="jAdjustment">${esc(j.adjustment||'')}</textarea><div class="grid2"><div><div class="label">Энергия: <span id="energyV">${j.energy||3}</span>/5</div><input class="range" id="jEnergy" type="range" min="1" max="5" value="${j.energy||3}" oninput="energyV.textContent=this.value"></div><div><div class="label">Фокус: <span id="focusV">${j.focus||3}</span>/5</div><input class="range" id="jFocus" type="range" min="1" max="5" value="${j.focus||3}" oninput="focusV.textContent=this.value"></div></div><button class="btn" style="margin-top:16px;width:100%" onclick="saveJournal(${d})">Сохранить запись</button></div><div class="card" style="margin-top:12px"><h3>Предыдущие записи</h3>${Object.keys(all).sort((a,b)=>b-a).slice(0,8).map(k=>`<button class="source" onclick="viewJournal(${k})">День ${k} · ${esc((all[k].learned||all[k].completed||'Без текста').slice(0,55))}</button>`).join('')||'<div class="muted">Пока нет записей.</div>'}</div>`}
function saveJournal(d){let all=store.get('journal',{});all[d]={completed:$('#jCompleted').value,learned:$('#jLearned').value,error:$('#jError').value,adjustment:$('#jAdjustment').value,energy:+$('#jEnergy').value,focus:+$('#jFocus').value,ts:Date.now()};store.set('journal',all);toast();renderJournal()}
function viewJournal(d){let j=store.get('journal',{})[d];if(!j)return;$('#modalBox').innerHTML=`<div class="row between"><h2>Agent Log · День ${d}</h2><button class="btn ghost" onclick="closeModal()">Закрыть</button></div><div class="label">COMPLETED</div><div>${esc(j.completed||'—')}</div><div class="label">LEARNED</div><div>${esc(j.learned||'—')}</div><div class="label">ERROR</div><div>${esc(j.error||'—')}</div><div class="label">ADJUSTMENT</div><div>${esc(j.adjustment||'—')}</div><p class="muted">Энергия ${j.energy}/5 · Фокус ${j.focus}/5</p>`;$('#modal').classList.remove('hidden')}
function renderProgress(){let done=S.data.days.filter(d=>dayDone(d.day)).length, exams=S.data.days.filter(d=>d.is_exam), examScores=store.get('examScores',{});let scores=store.get('skills',{PHY:0,COO:0,OBS:0,MEM:0,INT:0,COM:0,LAN:0,TEC:0,LDR:0,RES:0});let avg=Math.round(Object.values(scores).reduce((a,b)=>a+(+b||0),0)/10);let rank=avg>=90?'LEVEL 7 OPERATIVE':avg>=80?'SENIOR AGENT':avg>=70?'SPECIAL AGENT':avg>=55?'FIELD AGENT':avg>=40?'PROBATIONARY AGENT':'RECRUIT';$('#topSub').textContent='Статистика подготовки';$('#screen').innerHTML=`<section class="hero"><div class="eyebrow">PROGRESS</div><h1>${done} / 365 дней</h1><div class="progress"><span style="width:${Math.round(done/365*100)}%"></span></div><div class="row between" style="margin-top:12px"><span class="pill">${rank}</span><b>${avg}/100</b></div></section><div class="grid2" style="margin-top:12px"><div class="metric"><b>${done}</b><small>полных дней</small></div><div class="metric"><b>${Object.keys(store.get('journal',{})).length}</b><small>записей журнала</small></div><div class="metric"><b>${exams.filter(e=>examScores[e.day]!=null).length}</b><small>экзаменов оценено</small></div><div class="metric"><b>${totalPct()}%</b><small>курса закрыто</small></div></div><div class="card" style="margin-top:12px"><h3>10 направлений</h3>${Object.keys(scores).map(k=>`<div class="score-row"><span>${k}</span><input type="number" min="0" max="100" value="${scores[k]}" onchange="saveSkill('${k}',this.value)"></div>`).join('')}<div class="notice">Ставь оценки по результатам аттестаций и собственному прогрессу, а не по внешности или сравнению с другими.</div></div><div class="card" style="margin-top:12px"><h3>Экзамены и зачёты</h3>${exams.map(e=>`<div class="score-row"><button class="source" style="margin:0;text-align:left" onclick="openDay(${e.day})">День ${e.day}${e.day%30===0?' · аттестация':''}</button><input type="number" min="0" max="100" placeholder="0–100" value="${examScores[e.day]??''}" onchange="saveExam(${e.day},this.value)"></div>`).join('')}</div>`}
function saveSkill(k,v){let s=store.get('skills',{});s[k]=Math.max(0,Math.min(100,+v||0));store.set('skills',s);toast()}
function saveExam(d,v){let e=store.get('examScores',{});e[d]=Math.max(0,Math.min(100,+v||0));store.set('examScores',e);toast()}
function renderMore(){let sd=startDate()||'';$('#topSub').textContent='Материалы и настройки';$('#screen').innerHTML=`<section class="hero"><div class="eyebrow">RESOURCES</div><h1>Учебная база</h1><div class="muted">Основной курс работает офлайн. Внешние материалы открываются в браузере.</div></section><div class="card" style="margin-top:12px"><h3>Учебные ресурсы</h3><a class="source" target="_blank" rel="noopener" href="https://learnenglish.britishcouncil.org/">British Council LearnEnglish — английский</a><a class="source" target="_blank" rel="noopener" href="https://dictionary.cambridge.org/">Cambridge Dictionary — произношение и словарь</a><a class="source" target="_blank" rel="noopener" href="https://learngerman.dw.com/">DW Nicos Weg — немецкий</a><a class="source" target="_blank" rel="noopener" href="https://openstax.org/details/books/psychology-2e">OpenStax Psychology 2e — психология</a><a class="source" target="_blank" rel="noopener" href="https://www.khanacademy.org/math/statistics-probability">Khan Academy — статистика и вероятность</a><a class="source" target="_blank" rel="noopener" href="https://www.reuters.com/fact-check/">Reuters Fact Check — проверка информации</a><a class="source" target="_blank" rel="noopener" href="https://www.cisa.gov/secure-our-world">CISA Secure Our World — цифровая гигиена</a></div><div class="card" style="margin-top:12px"><h3>Установка на iPhone</h3><div class="notice">Открой приложение в Safari → «Поделиться» → «На экран Домой» → «Добавить». После первого открытия курс и прогресс доступны офлайн.</div></div><div class="card" style="margin-top:12px"><h3>Настройки курса</h3><div class="label">Дата старта</div><input class="input" type="date" id="startInput" value="${sd}"><button class="btn" style="margin-top:10px" onclick="saveStart()">Сохранить дату</button><button class="btn ghost" style="margin-top:10px;width:100%" onclick="exportData()">Экспорт прогресса (.json)</button><label class="btn ghost" style="display:block;text-align:center;margin-top:10px">Импорт прогресса<input type="file" accept="application/json" style="display:none" onchange="importData(this.files[0])"></label></div><div class="card" style="margin-top:12px"><h3>О безопасности</h3><p class="muted small">Курс не является подготовкой к реальной разведывательной или силовой деятельности. Физические занятия — общая подготовка. Единоборства, гимнастика, плавание и первая помощь — только в соответствующей безопасной среде и с квалифицированным инструктором, когда это требуется. Нет инструкций по оружию, взлому, слежке или опасным трюкам.</p></div>`}
function saveStart(){let v=$('#startInput').value;if(v){store.set('startDate',v);toast();render()}}
function exportData(){let keys=['startDate','checks','journal','examScores','skills'];let obj={};keys.forEach(k=>obj[k]=store.get(k,null));let blob=new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='academy-progress.json';a.click();URL.revokeObjectURL(a.href)}
function importData(file){if(!file)return;let r=new FileReader();r.onload=()=>{try{let o=JSON.parse(r.result);Object.entries(o).forEach(([k,v])=>{if(v!==null)store.set(k,v)});toast('Импортировано');render()}catch{toast('Ошибка файла')}};r.readAsText(file)}
function fmtTimer(s){let m=Math.floor(s/60),x=s%60;return `${String(m).padStart(2,'0')}:${String(x).padStart(2,'0')}`}
function setTimer(m){S.timerLeft=m*60;S.timerRunning=false;clearInterval(S.timer);updateTimer()}
function toggleTimer(){if(!S.timerLeft)S.timerLeft=25*60;S.timerRunning=!S.timerRunning;clearInterval(S.timer);if(S.timerRunning)S.timer=setInterval(()=>{S.timerLeft--;updateTimer();if(S.timerLeft<=0){clearInterval(S.timer);S.timerRunning=false;navigator.vibrate?.([200,100,200]);toast('Таймер завершён');renderToday()}},1000);renderToday()}
function resetTimer(){clearInterval(S.timer);S.timerRunning=false;S.timerLeft=0;updateTimer();renderToday()}
function updateTimer(){let e=$('#timerText');if(e)e.textContent=fmtTimer(S.timerLeft)}
$$('.nav button').forEach(b=>b.onclick=()=>{S.tab=b.dataset.tab;render();scrollTo(0,0)});$('#modal').addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});
fetch('data.json?v=19&build=academy').then(r=>r.json()).then(d=>{S.data=d;render()}).catch(e=>{$('#screen').innerHTML='<div class="empty">Не удалось загрузить курс. Открой приложение через веб-сервер/хостинг, а не как отдельный локальный файл.</div>'});

window.addEventListener('load',()=>{ if('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js?v=19&build=academy'); });
